<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine" nsURI="http://planet-mde.org/ttc2011/statemachine"
    nsPrefix="statemachine">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="#//Transition"
        eOpposite="#//Transition/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="#//Transition"
        eOpposite="#//Transition/dst"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//classifiers/Class"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="hu.bme.mit.viatra2.examples.reveng.stateTrace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//State"
        eOpposite="#//State/out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dst" lowerBound="1" eType="#//State"
        eOpposite="#//State/in"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass ../../org.emftext.language.java/metamodel/java.ecore#//references/IdentifierReference"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="hu.bme.mit.viatra2.examples.reveng.transitionTrace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
